name: Tag Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: env_tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add any steps needed for your deployment process
      - name: Deploy
        run: echo "Deploying to env_tag environment"
